### ISSUE TITLE
cannot build pagmo with nlopt  update

### ISSUE THREAD

**Issue by jschueller** [conda-forge/pagmo-feedstock#9]
Since nlopt has been updated to provide python bindings on windows too (https://github.com/conda-forge/nlopt-feedstock/pull/7) conda cannot resolve the dependency properly
(https://ci.appveyor.com/project/conda-forge/pagmo-feedstock/build/1.0.15/job/jmu3jopc4456y459)
and pulls an old version on py35 (unfortunately which has a wrong dll name and fails to be detected).

I see two options:
- 1. nlopt provides only the bindings, and a new package nlopt-c is created to provide the lib, with nlopt depending on nlopt-c
- 2. keep only pygmo, providing both lib and bindings

I'd prefer 2. so as to stick to "keep it simple", unless there a arguments to have a pagmo package.
I guess it would be feasible as the build time would be less that 34(lib)+9 mins (bindings).

**Comment by bluescarni** [comment]
@jschueller I am not sure I understand the problem. Our recipe does not seem to have differences between python 3.5 and 3.6, and the pagmo package does not use python in any form (its sister package, pygmo, does interact with the conda python stack).

**Comment by jschueller** [comment]
the problem lies in the dependency resolution of nlopt on windows: as the nlopt package must match a python version and pagmo does not, conda cannot resolve properly the dependency.

**Comment by isuruf** [comment]
@jschueller, I think conda is getting confused because of a broken package. @conda-forge/core can you remove `win-64/nlopt-2.4.2-py35_1.tar.bz2` and `win-32/nlopt-2.4.2-py35_1.tar.bz2` ?

**Comment by jschueller** [comment]
It's pulling win-64/nlopt-2.4.2-0.tar.bz2 (an old non-python version), how would that change this ?

**Comment by isuruf** [comment]
That's the only difference I see between python 3.5 and 3.6. Sometimes the conda resolver gets confused. I'm not sure if it'll fix it, but worth a try.

**Comment by ocefpaf** [comment]
> @conda-forge/core can you remove `win-64/nlopt-2.4.2-py35_1.tar.bz2` and `win-32/nlopt-2.4.2-py35_1.tar.bz2` ?

Moved them to a broken `label`. Let me know if that helps.
